import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { readCanonical } from './readWorkbook'
import { buildProblem, solve, summarize } from './solve'
import { validate } from './validate'

// The real per-grade starter files (generated by scripts/make_real_workbooks.py).
// Skipped if they aren't present (they're git-ignored, like the Python workbook).
const path = fileURLToPath(
  new URL('../../../docs/canonical-data-grade8-REAL.xlsx', import.meta.url),
)
const maybe = existsSync(path) ? describe : describe.skip

maybe('real grade-8 workbook end-to-end', () => {
  it('parses, validates clean, and solves with no unfilled slots or repeats', async () => {
    const buf = readFileSync(path)
    const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength)
    const { canonical, issues: readIssues } = await readCanonical(ab)
    const issues = [...readIssues, ...validate(canonical)]

    expect(issues.filter((i) => i.severity === 'error')).toEqual([])
    expect(canonical.grade).toBe(8)

    const problem = buildProblem(canonical)
    const result = solve(problem)
    const summary = summarize(canonical, problem, result)

    expect(summary.students).toBe(206)
    expect(summary.unfilled).toBe(0)
    expect(summary.repeats).toBe(0)
    // Spanish/German (year-long, enrolled) must not be in the elective wheel
    expect(problem.offerings.some((o) => o.course_id === 3593 || o.course_id === 3547)).toBe(false)
  })
})
